# -*- coding: utf-8 -*-
"""Copia de Class2-3765.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EhFr5PypAXqpJr7NK7Wd9lHsU-quzsQE

#**OPERADORES MATEMÁTICOS EN PTYHON**
"""

num1 = 4
num2 = 3
res = num1 + num2
print(res)

# Default Input() = str
num1 = int(input("Digite el número 1: "))
num2 = int(input("Digite el número 2: "))
res = num1 + num2
print("La suma de {} y {} es = {}".format(num1, num2, res ))
print(f"La suma de {num1} y {num2} es = {res}")

try:
  num = input("Digite el número: ")
  num  =int(num)
except ValueError:
  print("No es valido el Intero!!")

num = input("Digite el número: ")
num  =int(num)

"""**CALCULADORA** + - * /"""

num1 = int(input("Digite el número 1: "))
num2 = int(input("Digite el número 2: "))

suma = num1 + num2
resta = num1 - num2
multi = num1 * num2
divi = num1 / num2

print("\nEl reultado de la SUMA es= {}".format(suma))
print("\nEl reultado de la RESTA es= {}".format(resta))
print(f"\nEl resultado de la MULTIPLICACIÓN es= {multi}")
print(f"\nEl resultado de la DIVISIÓN es= {divi}")

"""Se recibe una venta por concepto de un prodcuto se requiere aplicar el IVA (19%) y conocer el total a pagar con el IVA Incluido"""

# variable que captura la venta
venta = float(input("¿Cuánto fue el total de la compra?: "))
iva = venta * 0.19
total = venta + iva
print("El IVA es = ${:,.0f} y el total a pagar es = ${:,.0f}".format(iva, total))
print(f"El IVA es = ${iva:,.0f} y el total a pagar es = ${total:,.0f}")

"""Se necesita un sistema que reciba tres calificaciones parciales de un alumno y en base a estas darle su promedio

"""

cal1 = float(input("Digite la calificación 1: "))
cal2 = float(input("Digite la calificación 2: "))
cal3 = float(input("Digite la calificación 3: "))

prom = round((cal1 + cal2 + cal3)/3, 2)

print(f"El promedio es= {prom}")

"""# **Taller Refuerzo**
https://drive.google.com/file/d/1jFH9DgCRha_dn9JG7c_jjTpeE5x5kK3d/view?usp=sharing

Un alumno desea saber cuál será su calificación final en la materia de  algoritmos. Dicha calificación se compone de tres exámenes parciales.
"""

examen1 = 30/100
examen2 = 30/100
examen3 = 40/100

nota1 = float(input("Nota primer examen: "))
nota2 = float(input("Nota primer examen: "))
nota3 = float(input("Nota primer examen: "))

notafinal = round(examen1*nota1 + examen2*nota2 + examen3*nota3, 2)

if notafinal >= 6:
    print("¡Pasaste la materia con {}!".format(notafinal))
else:
  print("¡Debes repetir!", f"Sacaste {notafinal}")

"""Un maestro desea saber qué porcentaje de hombres y que
porcentaje de mujeres hay en un grupo de estudiantes.
"""

import matplotlib.pyplot as plt

mujeres = int(input("Ingresa el numero de mujeres: "))
hombres = int(input("Ingresa el numero de hombres: "))
total_alumnos = mujeres + hombres
print("El total de alumnos es >>> ", total_alumnos)
#print(f"¡El porcenjate de mujeres es de: {(mujeres / total_alumnos)*100:,.0f} %")
#print(f"¡El porcenjate de hombres es de: {(hombres / total_alumnos)*100:,.0f} %")
print()
sexo = [mujeres,hombres]
genero = ["Mujeres","Hombres"]
colores = ["#EE6055","#60D394"]
desfase = (0, 0.1)
plt.pie(sexo, labels=genero, autopct="%0.0f %%", colors=colores, explode=desfase)
plt.axis("equal")
plt.show()

"""Un vendedor recibe un sueldo base más un 10% extra por comisión de sus ventas, el vendedor desea saber cuánto dinero obtendrá por concepto de comisiones por las tres ventas que realiza en el mes y el total que recibirá en el mes tomando en cuenta su sueldo base y comisiones."""

import matplotlib.pyplot as plt
fig, ax = plt.subplots()

salario = 1000000
comision = 0.10
venta1 = float(input("Ingrese la venta 1:"))
venta2 = float(input("Ingrese la venta 2:"))
venta3 = float(input("Ingrese la venta 3:"))
print()
total_ventas = venta1 + venta2 + venta3
print(f"Total ventas : ${total_ventas:,.0f}")
ax.barh([1, 2, 3], [venta1, venta2, venta3])
plt.show()


total_comision = total_ventas * comision
print(f"Comision devengada : ${total_comision:,.0f}")
print("********************")
sueldo = salario + total_comision
print(f"Salario a pagar : ${sueldo:,.0f}")