# -*- coding: utf-8 -*-
"""Copia de class3-3765.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UfUM408KJgqyONyoSzpZcXTDQ1IkSN9g

#***SENTENCIAS CONDICIONALES EN PYTHON***
"""

num1 = 5
num2 = 5

if num1 == num2:
  print("Los números son iguales")
else:
  print("Los números NO son iguales")

"""**OPERADORES RELACIONAES**

**>** mayor que, **<** menor que, **>=** mayor o igual que, **<=** menor o igual que, **==** igual que, **!=** diferente que,ambos debe ser iguales **and**, uno de los debe ser verdadero **or**, **in** texto inmerso en otro
"""

usuario = input("Digite su usuario: ")
usubd = "carlos1708"

if usuario == usubd:
  print("El usuario es Correcto!")
else:
  print("EL usuario es Incorrecto")

num = int(input("Digite el  número: "))

if num > 20:
  print("EL número es mayor a 20")
elif num > 15:
  print("EL número es mayor a 15")
elif num > 10:
  print("EL número es mayor a 10")
elif num > 5:
  print("EL número es mayor a 5")
else:
  print("No se cumple ninguna condición!!!")

edad = int(input("Digite su edad: "))

if edad >= 13 and edad < 20:
  print("Eres un Adolscente")
else:
  print("NO eres un Adolscente")

#palabra = input("Digite la palabra")

if "10" in "10000":
  print("Verdadero!!")
else:
  print("Falso!!")

"""Se necesita un sistema para un supermercado, el cual dará un 10% de descuento a las personas que compren más de $1000000 de lo contrario no dará ningún descuento, al cliente se le debe de dar el total a pagar. Condicional."""

compra = float(input("¿Cuánto fue el total de la compra?: $"))

if compra > 1000000:
  descu = compra * 0.10
  total = compra - descu
  print("EL descuento es =${:,.0f} y el total a pagar es=${:,.0f}".format(descu, total))
else:
  print(f"No tiene descuento, el total a pagar es= ${compra:,.0f}")

"""Se necesita un sistema que reciba tres calificaciones parciales de un alumno y en base a estas darle su promedio donde si el promedio es menor a 3.0 se le dirá que esta reprobado, en caso contrario el mensaje será aprobado. Condicional."""

cal1 = float(input("Digite la calificación 1: "))
cal2 = float(input("Digite la calificación 2: "))
cal3 = float(input("Digite la calificación 3: "))

prom = round((cal1 + cal2 + cal3)/3, 2)

if prom < 3.0:
  estado = "Reprobó--"
else:
  estado = "Aprobó++"
print(f"El promedio es = {prom} y el estado es= {estado}")

"""**Taller 2:**

Dando continuidad con la primera entrega del proyecto, en esta oportunidad el estudiante debe realizar las siguientes validaciones utilizando la sentencia condicional IF.
1.	Si el empleado es mayor de 55 años disfrutará de un bono de prepensión correspondiente al 5% de su sueldo básico.
2.	Si el empleado es casado y tiene hijos se le otorgará un paseo cada diciembre
 
3.	Si el sueldo básico está entre 1000000 y 1500000 tendrá una comisión del 2% sobre el valor del sueldo; Si el sueldo básico está entre 1500001 y 2000000 tendrá una comisión del 5% sobre el valor del sueldo; para todos los demás casos no habrá comisión.
4.	Si el empleado trabajó más de 20 días al mes y su sueldo es menor a 1000000 tendrá derecho a un bono de alimentación.
"""

edad = int(input("ingrese su edad: "))
salario = float(input("Ingrese su salario: "))
estado_civil = ["soltero", "casado", "Ulibre"]
indice = int(input("Cual es su estado civil : \n 0 - Soltero\n 1 - Casado\n 2 - U Libre\n selecciona un numero de la lista: "))
valor_seleccionado = estado_civil[indice]
dias_trabajados = int(input("Ingrese los dias trabajados: "))
print("El valor seleccionado es:", valor_seleccionado)
print("Cual es tu salario : $", salario)
print("**********************")
tiene_hijos = input("¿Tiene hijos? (responda 'si' o 'no'): ") == "si"
if tiene_hijos:
    print("Tiene hijos.")
else:
    print("No tiene hijos.")
print("**********************")
print()
#bono x edad
print("Resultados beneficios:")
if edad > 55 or estado_civil == "casado" or tiene_hijos == "si":
  print("tienes un bono de prepension")
  prepension = salario*0.05 + salario
  print("Y tu salario es de : $", prepension)
  print("tienes un paseo en diciembre")
else:
  print("Desafortunadamente no tiene beneficios!")
# comision
if salario >= 1000000 and salario < 1500000 and estado_civil == "casado" and tiene_hijos == "si":
  print(f"Tienes una comision del 2% y tu sueldo total es de: {salario * 0.02 + salario}" )
  print("tienes un paseo en diciembre")
elif salario >= 1501000 and salario < 2000000 or estado_civil == "casado" or tiene_hijos == "si":
  print(f"Tienes una comision del 5% y tu sueldo total es de: {salario * 0.05 + salario}" )
# 20 dias y meno a 10000000
if dias_trabajados >= 20 and salario < 1000000 and estado_civil == "casado" and tiene_hijos == "si":
  print("Tienes un bono de alimentación.")
  print("tienes un paseo en diciembre")
else:
  print("No recibes mas beneficios!")
  
print("Cual es tu salario : $", salario+prepension)

edad = int(input("Ingrese la edad del empleado: "))
sueldo_basico = float(input("Ingrese el sueldo básico del empleado: "))
es_casado = input("¿El empleado está casado? (responda 'si' o 'no'): ") == 'si'
tiene_hijos = input("¿El empleado tiene hijos? (responda 'si' o 'no'): ") == 'si'
dias_trabajados = int(input("Ingrese la cantidad de días trabajados en el mes: "))
print("**************************")

# tiene más de 55 años
if edad > 55:
    bono_prepension = sueldo_basico * 0.05
    print(f"El empleado recibirá un bono de prepensión de $ {bono_prepension:,.0f}")
else:
  bono_prepension = 0
  print("No tienes bono de prepension!")
if es_casado and tiene_hijos:
    print("adicionalmente recibe un paseo en diciembre")
else:
   print("No piensas casarte o tener hijos?")
# if sueldo_basico <= 1500000 and  sueldo_basico <= 1000000 
if 1000000 <= sueldo_basico <= 1500000:
    comision = sueldo_basico * 0.02
    print(f"y tienes una comisión del 2% sobre el valor del sueldo de $ {comision:,.0f}, para un total de ${comision + sueldo_basico + bono_prepension:,.0f}" )
elif 1500001 <= sueldo_basico <= 2000000:
    comision = sueldo_basico * 0.05
    print(f"y tienes una comisión del 5% sobre el valor del sueldo de $ {comision:,.0f}, para un total de ${comision + sueldo_basico + bono_prepension:,.0f}")

# si el empleado trabajó más de 20 días al mes y su sueldo es menor a 1000000
if dias_trabajados > 20 and sueldo_basico < 1000000:
    bono_alimentacion = 100000
    print(f"El empleado recibirá un bono de alimentación de $ {bono_alimentacion:,.0f}")