# -*- coding: utf-8 -*-
"""clase1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EOIc1fBXfMDvZcdEXv4F-0fRQl1eUyeS
"""

# comentario
nombre = "Mauricio"
apellido = "Pena"
edad = 40
print (nombre +" "+ apellido,"\ntiene" ,edad)
nombres = input("Digite su nombre ")
print (nombres)

# No de Identificación, Nombres, Apellidos, Dirección, Teléfono, Edad, Estado Civil, Número de hijos, Estatura en centímetros, fecha de contratación (Día/mes/año), Sueldo básico, Días Laborados.
from datetime import date, datetime
identificacion = int(input("Digite su identificación: "))
nombres = input("Digite su nombre: ")
apellidos = input("Digite sus apellidos: ")
direccion = input("Digite sus direccion: ")
telefono = int(input("Digite sus telefono: "))
edad = int(input("Digite sus edad: "))
estado_civil = input("Digite sus estado civil: ")
num_hijos = int(input("Número de hijos: "))
estatura = int(input("Digite sus estatura en cms: "))
fecha_ini = input("Digite sus fecha de inicio: ")
salario = float(input("Digite su salario: "))
dias_lab = 12
#Día actual
today = date.today()
#Fecha actualwe
now = datetime.now()

print("*****************************\nEl usuario:", identificacion,"con nombre: ",nombres, apellidos,"\n",direccion,"y ",telefono,"\nDe: ",edad, "años",",",estado_civil,"y mide:" ,estatura,"cms \n Comenzo labores el:" ,fecha_ini," con un salario:" ,"{:,}".format(salario).replace(',','~').replace('.',',').replace('~','.'),"\n Ha laborado:" ,dias_lab,"días \n*****************************")
print("informe realizado el:", today,now)

from datetime import datetime, timedelta
def obtener_tiempo_transcurrido(segundos):
    dias = int(segundos / 60 / 60 / 24)
    segundos -= dias * 60 * 60 * 24
    horas = int(segundos / 60 / 60)
    segundos -= horas*60*60
    
    minutos = int(segundos/60)
    segundos -= minutos*60
    return f"{dias} días, {horas} horas, {minutos} minutos y {segundos} segundos"


ahora = datetime.now()
futuro = ahora + timedelta(hours=50, seconds=925)
diferencia = futuro-ahora

legible = obtener_tiempo_transcurrido(diferencia.total_seconds())
print(legible)

import pandas as pd
import numpy as np
import datetime
from datetime import date

# Generamos un ejeplo de datos 
date1 = pd.Series(pd.date_range('2019-1-1 12:00:00', periods=7, freq='M'))
date2 = pd.Series(pd.date_range('2019-6-18 21:45:00', periods=7, freq='W'))
df = pd.DataFrame(dict(Start_date = date1, End_date = date2))

# Calculamos diferencias de días hábiles
df['diff_days'] = df.apply(lambda row : np.busday_count(row['Start_date'].date(),row['End_date'].date()),axis=1)

print(df)

"""# **Operadores Matemáticos**"""

from pandas.core.indexes.datetimes import prefix_mapping
num1 = int(input("ingrese el numero: "))
num2 = int(input("ingrese el numero: "))
res = num1 + num2
print("La suma de {} y {} es = {} ".format(num1, num2, res))
print(f"La suma de {num1} y {num2} es = {res}")

try:
  num = input("Digite el numero: ")
  num = int(num)
except ValueError:
  print("NO es un numero valido")

my_list = [1, 2]
 
for v in range(2):
    my_list.insert(-1, my_list[v])
 
print(my_list)

def message():
    print("Ingresar valor: ")
 
message()
a = int(input())
message()
b = int(input())
message()
c = int(input())